server:
  port: 7001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_edu?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: edu-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#使用redis作为缓存
  redis:
    port: 6379
    host: 192.168.92.11
logging:
  level:
    com.mrpeng: debug


mybatis-plus:
  mapper-locations: classpath*:/com/mrpeng/eduserver/mapper/xml/*.xml
